version: '3.8'

services:
  backend:
    build:
      context: ./Employee_Attrition/backend
    ports:
      - "8001:8001"
    volumes:
      - ./Employee_Attrition/backend:/app
      - model-data:/app/pickle/models
    environment:
      - DEBUG=True
      - SECRET_KEY=development-secret-key
      - ALLOWED_HOSTS=localhost,127.0.0.1
    restart: unless-stopped

  frontend:
    build:
      context: ./Employee_Attrition/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8001/api
    restart: unless-stopped

volumes:
  model-data:
    driver: local