# app-logs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-logs-pvc
  namespace: employee-attrition
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi