apiVersion: apps/v1
kind: Deployment
metadata:
  name: attrition-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attrition-backend
  template:
    metadata:
      labels:
        app: attrition-backend
    spec:
      containers:
      - name: attrition-backend
        image: siddhesh01/employee_attrition1-backend:latest
        imagePullPolicy: Never  # For local testing
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: model-storage
          mountPath: /app/pickle/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: attrition-backend
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP