apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: employee-attrition
spec:
  selector:
    app: attrition-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer