apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: employee-attrition
data:
  default.conf: |
    server {
        listen 80;
        
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
        
        location /api/ {
            proxy_pass http://backend-service:8001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Direct pass for models endpoint
        location /models/ {
            proxy_pass http://backend-service:8001/models/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Direct pass for prediction endpoint
        location /prediction/ {
            proxy_pass http://backend-service:8001/prediction/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }